name: hpe
channels:
  - defaults
dependencies:
  - python=3.5
  - _tflow_select
  - absl-py=0.4.1=py35_0
  - astor=0.7.1=py35_0
  - blas=1.0=mkl
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12
  - certifi=2018.8.24=py35_1
  - cloudpickle=1.0.0=py_0
  - cudatoolkit
  - cudnn
  - cycler=0.10.0
  - dask-core=1.2.2=py_0
  - dbus=1.13.6
  - decorator=4.4.0=py_0
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.0=py35_0
  - glib=2.56.2
  - graphite2=1.3.13
  - grpcio=1.12.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.4.1
  - intel-openmp=2019.3
  - jasper=2.0.14
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc
  - libgfortran-ng
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.6.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxml2=2.9.9
  - markdown=2.6.11=py35_0
  - matplotlib=3.0.0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6
  - ncurses=6.1
  - networkx=2.3=py_0
  - numpy=1.13.3
  - olefile=0.46=py35_0
  - opencv=3.4.2
  - openssl=1.0.2r
  - pcre=8.43
  - pillow=5.2.0
  - pip=10.0.1
  - pixman=0.38.0
  - protobuf=3.6.0
  - py-opencv=3.4.2
  - pyopengl=3.1.1a1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2019.1
  - pywavelets=1.0.0
  - qt=5.9.6
  - readline=7.0
  - scikit-image=0.14.0
  - scipy=1.1.0
  - setuptools=40.2.0
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.28.0
  - tensorboard=1.10.0
  - tensorflow=1.10.0
  - tensorflow-base=1.10.0
  - termcolor=1.1.0
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1.1
  - werkzeug=0.15.2=py_0
  - wheel=0.31.1=py35_0
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cython==0.29.7
    - glfw==1.8.0

